### ISSUE TITLE
Why are pre-release buildtools required?

### ISSUE THREAD

**Issue by ghost** [ScreamingHawk/fate-sheets#19]
It's not a good practice to require pre-release buildtools like 26-rc1 to build own releases. I forcefully downgrade to 25.0.2 and it still seems to work. Any issues that I might have overlooked or what caused the upgrade?

**Comment by ScreamingHawk** [comment]
One of the pull requests I received had the pre-release build tools and I decided to keep it as a way to remind myself to build to Android O on release. 

There's no harm in lowering the build tools version. 

I've since found another method to remind me of this so will change the build tools to 25.0.3. 

Thanks for the comment, I'd completely forgotten about this and it's nice to see other people have an interest.
