### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by fabiocosta0305** [ScreamingHawk/fate-sheets#27]
It could be good to put a way to translate the Character Sheets and text for other languages. I put myself available to translate for Brazilian Portuguese as by the official Fate publishing @ solarentrenimento.com.br

**Comment by ScreamingHawk** [comment]
Translations is absolutely something I want for Fate Sheets! 

But maintaining translations can be a pain (especially since I'm not fluent in any other languages), so I'm planning to wait until the application has a few more features (World Creation Sheet etc) before making this request. 

I'll close this ticket until I'm ready to accept translations.
