### ISSUE TITLE
Custom Aspects/Skills

### ISSUE THREAD

**Issue by fabiocosta0305** [ScreamingHawk/fate-sheets#28]
It would be nice to put a custom option for settings that go away from the default Aspects, like _Masters of Umdaar_ or _Loose Threads_. Also, it could be nice if you could put custom Skills, like used in _Wearing the Cape_

**Comment by ScreamingHawk** [comment]
I think both these already exist. Correct me if I'm wrong. 

The skills list can already be customised. From the character sheet list screen (the home/main screen), click the options menu button on the top right, then select **Edit Skills List**. Any skills you add can be applied to any character sheet you have. Does this cover the custom skills request? 

Aspects in Fate Sheets is a free text field so you can add whichever custom aspects you like, because all aspects are custom. Are you just looking to differentiate between *permanent* and *temporary* aspects? Should you instead be using the *Extras* section for temporary aspects? https://fate-srd.com/fate-core/extras

I'm not familiar with *Masters of Umdaar*, *Loose Threads* or *Wearing the Cape*, so please help me understand if I am missing something.

**Comment by ScreamingHawk** [comment]
No correction, assuming my answer was sufficient

**Comment by RJEdlin** [comment]
This might need to be more discoverable on the skills page. Many people don't adhere strictly to a pre-decided skill list (e.g. a ship will have different skills from a typical creature; if you treat a condition like poison as a character, you might want to give the poison a unique skill like Potency just for that, etc.) and will want to add skills on the fly. Allowing the user to add to the skill list in the same context that they give characters skills, or even better, allowing the user to assign skills not in the skill list to characters without altering the skill list, would be a significant improvement to usability.
